import type { NextPage } from 'next'
import Header from 'next/head'
import Matrix from '../components/Matrix'
import styles from '../styles/Index.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Header>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Header>
      <div className={styles.main}>
        <Matrix />
      </div>
    </div>
  )
}

export default Home
